language: ruby
rvm:
- 2.2.2

env:
- NODE_VERSION="0.12"

cache:
- bundler
- apt

before_install:
- nvm install node
- npm install -g gulp
- npm install

script:
- gulp production
- bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
