# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aleksandr Fesenko
name:  Blog - Aleksandr Fesenko
author:
  name: Aleksandr
  email: aleksandr.fesenko@smithua.com
email: aleksandr.fesenko@smithua.com
description: > # this means to ignore newlines until "baseurl:"
 Front-End Developer from Ukraine
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.smithua.com" # the base hostname & protocol for your site
twitter_username: smithua
github_username:  smithua

# Build settings
markdown: kramdown

# include pages folder
include: ["_pages"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
